#!/bin/sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
OUT_DIR="${OUT_DIR:-$ROOT_DIR/dist/spotify-playlist-builder-template}"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

copy_path() {
  src="$1"
  dest="$OUT_DIR/$src"
  if [ -d "$ROOT_DIR/$src" ]; then
    mkdir -p "$dest"
    (cd "$ROOT_DIR/$src" && tar \
      --exclude='__pycache__' \
      --exclude='*.pyc' \
      --exclude='.pytest_cache' \
      -cf - .) | (cd "$dest" && tar -xf -)
  elif [ -f "$ROOT_DIR/$src" ]; then
    mkdir -p "$(dirname "$dest")"
    cp "$ROOT_DIR/$src" "$dest"
  fi
}

# Core application files
for path in \
  api_server.py \
  config.py \
  docker-compose.yml \
  Dockerfile \
  matcher.py \
  playlist_builder.py \
  playlist_io.py \
  reorder.py \
  requirements.txt \
  spotify_client.py \
  README.md \
  .env.example \
  .gitignore
 do
  copy_path "$path"
done

# Helpful scripts and docs, excluding installation-specific wrappers if absent.
mkdir -p "$OUT_DIR/scripts" "$OUT_DIR/docs" "$OUT_DIR/playlists" "$OUT_DIR/config"
copy_path "scripts/synology-sync-and-autobuild.sh"
copy_path "docs/shareable-template.md"

# Replace personal playlist data with safe samples.
cat > "$OUT_DIR/playlists/example_open_road.csv" <<'CSV'
Title,Artist,Album,Year
Take On Me,a-ha,Hunting High and Low,1985
Girls Just Want to Have Fun,Cyndi Lauper,She's So Unusual,1983
Walking on Sunshine,Katrina and the Waves,Katrina and the Waves,1985
Don't You (Forget About Me),Simple Minds,The Breakfast Club,1985
Everybody Wants to Rule the World,Tears for Fears,Songs from the Big Chair,1985
CSV

cat > "$OUT_DIR/config/playlist_targets.csv" <<'CSV'
playlist_key,playlist_id,playlist_name
example-open-road,,Example Open Road Playlist
CSV

cat > "$OUT_DIR/QUICKSTART.md" <<'MD'
# Spotify Playlist Builder Quickstart

This is a clean template copy. It does not include the original owner's Spotify credentials, token cache, personal playlists, or Spotify playlist IDs.

## 1. Create a Spotify Developer app

Create an app in the Spotify Developer Dashboard and add this redirect URI:

```text
http://127.0.0.1:8888/callback
```

## 2. Configure credentials

```bash
cp .env.example .env
```

Edit `.env` and add your own Spotify Developer app credentials.

## 3. Start the API

```bash
docker compose up -d --build
curl http://127.0.0.1:5150/health
```

## 4. Build the sample playlist

```bash
curl -X POST http://127.0.0.1:5150/build/example-open-road \
  -H "Content-Type: application/json" \
  -d '{"dry_run":false,"search_limit":50}'
```

## 5. Add your own playlist

Create a CSV under `playlists/` with exactly this header:

```csv
Title,Artist,Album,Year
```

Example filename:

```text
playlists/my_party_mix.csv
```

That becomes playlist key:

```text
my-party-mix
```

Build it:

```bash
curl -X POST http://127.0.0.1:5150/build/my-party-mix \
  -H "Content-Type: application/json" \
  -d '{"dry_run":false,"search_limit":50}'
```

To update the same Spotify playlist later, save its Spotify playlist ID in `config/playlist_targets.csv`.
MD

cat > "$OUT_DIR/.template-export-notes.txt" <<'TXT'
Generated by scripts/export-shareable-template.sh.
Review this folder before sharing.
Do not copy real .env files, token caches, private reports, or personal playlist IDs into this package.
TXT

printf 'Created clean template package: %s\n' "$OUT_DIR"
printf 'Review it, then zip or publish that folder as a separate template repo.\n'
